# Generated by Django 3.0.3 on 2020-07-12 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20200712_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='author',
            new_name='category',
        ),
    ]
